source.. = src/
output.. = bin/
jars.compile.order = .
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               LICENSE.TXT,\
               libs/box-java-sdk-4.16.4.jar,\
               libs/jose4j-0.9.6.jar,\
               libs/minimal-json-0.9.5.jar
src.includes = LICENSE.TXT,\
               plugin.xml,\
               build.properties,\
               META-INF/
bin.excludes = maven.properties
