source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               CHANGELOG.md,\
               resources/,\
               LICENSE.TXT,\
               libs/sshd-common-2.16.0.jar,\
               libs/sshd-core-2.16.0.jar,\
               libs/sshd-putty-2.16.0.jar,\
               libs/sshd-sftp-2.16.0.jar
src.includes = LICENSE.TXT,\
               META-INF/,\
               resources/,\
               build.properties,\
               pom.xml
bin.excludes = maven.properties
